In [1]:
import pandas as pd
import numpy as np
import ast
import json
import os
from essentia.standard import MonoLoader

2023-03-24 15:49:01.571441: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[   INFO   ] MusicExtractorSVM: no classifier models were configured by default
2023-03-24 15:49:01.953762: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-24 15:49:01.956966: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2023-03-24 15:49:01.961607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:01.961627: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2023-03-24 15:49:01.965190: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2023-03-24 15:49:01.965230: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2023-03-24 15:49:01.986238: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2023-03-24 15:49:01.986501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2023-03-24 15:49:01.986884: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2023-03-24 15:49:01.987442: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2023-03-24 15:49:01.987579: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2023-03-24 15:49:01.987888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.524457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.524481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.524485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.525000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.530080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.530322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.530338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.530342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.530345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.530591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.534245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.534480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.534493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.534497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.534500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.534744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.837327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.838091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.838134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.838148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.838160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.838921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.856951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.857425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.857454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.857462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.857470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.857967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.861799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.862127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.862148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.862154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.862159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.862486: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.867861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.868186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.868206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.868212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.868218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.868549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.869026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.869331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.869345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.869350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.869355: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.869682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.871100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.871406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.871420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.871425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.871430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.871715: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.873189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.873432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.873453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.873457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.873460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.873714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.874843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.875064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.875074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.875079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.875082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.875312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.876990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.877217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.877227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.877231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.877234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.877464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.880105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.880333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.880346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.880349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.880353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.880585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.886549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.887274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.887313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.887325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.887337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.888088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.893694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.894280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.894316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.894327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.894336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.894941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.900403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.900991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.901024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.901034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.901044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.901663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.905375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.905796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.905820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.905827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.905833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.906271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.910398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0

In [2]:
from tqdm.notebook import tqdm

name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.910808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.910832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.910839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.910846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.911266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
2023-03-24 15:49:02.914325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: NVIDIA GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.65GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2023-03-24 15:49:02.914617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2023-03-24 15:49:02.914635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-24 15:49:02.914640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2023-03-24 15:49:02.914645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2023-03-24 15:49:02.914943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8861 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)

In [3]:
tqdm.pandas()

In [4]:

args = pd.Series({
    "root_dir":"/mnt/disks/data/",
    "dataset_path":"/mnt/disks/data/fma/fma_large",
    "embeddings":"music_style",
    "train_id": "hierarchical_mini_test",
    'sample_size':0.01
})

In [5]:



job_path = "/mnt/disks/data/fma/trains"


# In[15]:


train_path = os.path.join(job_path,args.train_id)


# In[16]:


base_path = os.path.join(args.root_dir,"fma")


# In[17]:


models_path = os.path.join(args.root_dir,"models")


metadata_path_fma = os.path.join(base_path,"fma_metadata")


# In[18]:


metadata_file = os.path.join(train_path,"metadata.json")


categories_labels_path = os.path.join(train_path,"labels.json")

In [6]:


def __load_json__(path):
    with open(path, 'r') as f:
        tmp = json.loads(f.read())

    return tmp

In [7]:

def create_dir(path):
    # checking if the directory demo_folder2 
    # exist or not.
    if not os.path.isdir(path):

        # if the demo_folder2 directory is 
        # not present then create it.
        os.makedirs(path)
    return True

In [8]:
create_dir(train_path)

True

## Load genres file. Contains relationships beetwen genres

In [9]:
genres_df = pd.read_csv(os.path.join(metadata_path_fma,'genres.csv'))

In [10]:
genres_df

     genre_id  #tracks  parent          title  top_level
0           1     8693      38    Avant-Garde         38
1           2     5271       0  International          2
2           3     1752       0          Blues          3
3           4     4126       0           Jazz          4
4           5     4106       0      Classical          5
..        ...      ...     ...            ...        ...
158      1032       60     102        Turkish          2
159      1060       30      46          Tango          2
160      1156       26     130           Fado          2
161      1193       72     763      Christmas         38
162      1235    14938       0   Instrumental       1235

[163 rows x 5 columns]

In [95]:
genres_df[genres_df['genre_id'] == 495]

     genre_id  #tracks  parent      title  top_level
136       495     2061      15  Downtempo         15

In [106]:
# Cria um dicionário que associa o ID de cada música aos IDs de seus gêneros musicais
tracks_df = pd.read_csv(os.path.join(metadata_path_fma,'tracks.csv'), header=[0,1], index_col=0)

In [107]:
tracks_df[['track']].sample(20)

            track                                                              \
         bit_rate comments composer         date_created        date_recorded
track_id
15917      192000        0      NaN  2009-07-02 12:48:21                  NaN
25272       64000        0      NaN  2010-02-12 14:06:15                  NaN
142571     263254        0      NaN  2016-09-03 10:17:41                  NaN
80748      256000        0      NaN  2013-03-22 15:37:29                  NaN
123831     224964        0      NaN  2015-08-20 08:37:00                  NaN
137896     320000        0      NaN  2016-05-26 02:21:21                  NaN
7047       280092        0      NaN  2009-03-04 14:04:29                  NaN
121854     192000        0      NaN  2015-06-25 16:02:19                  NaN
125641     320000        0      NaN  2015-09-28 06:54:45                  NaN
53375      192000        0      NaN  2011-09-02 20:47:31                  NaN
146556     320000        0      NaN  2016-11-18 19:07:05  2013-06-29 00:00:00
106926     320000        0      NaN  2014-06-23 13:56:50                  NaN
98478      319932        0      NaN  2014-02-03 00:08:59                  NaN
50442      192000        0      NaN  2011-07-06 13:15:32                  NaN
149972     167889        0      NaN  2017-01-24 22:10:49                  NaN
116330     192000        0      NaN  2015-03-13 12:06:52                  NaN
40952      256000        0      NaN  2010-12-17 16:52:02                  NaN
137475     320000        0      NaN  2016-05-18 03:06:23                  NaN
58078      192000        0      NaN  2011-12-26 20:09:10                  NaN
147766     188758        0      NaN  2016-12-14 17:08:56                  NaN

                                                               \
         duration favorites      genre_top             genres
track_id
15917         372         0            NaN       [26, 38, 76]
25272         198         1            NaN          [32, 107]
142571        269         1  International               [79]
80748         256         0            NaN          [17, 130]
123831        259         2           Rock               [88]
137896        180         2        Hip-Hop               [21]
7047           98         8            NaN   [10, 12, 25, 32]
121854        238        24            NaN     [18, 38, 1235]
125641        301         1            NaN      [15, 38, 236]
53375         237         1        Hip-Hop              [100]
146556        336         1            NaN      [15, 70, 107]
106926        340         2            NaN  [26, 38, 66, 359]
98478         345         0   Experimental      [38, 41, 250]
50442         420         5            NaN      [15, 21, 100]
149972       1026         0            NaN       [38, 41, 76]
116330        285         0            NaN                 []
40952         194         0           Rock               [12]
137475        870         0   Experimental      [38, 41, 247]
58078         359         1            NaN       [1, 38, 187]
147766        277         1           Rock           [12, 85]

                                   \
                       genres_all
track_id
15917        [38, 10, 12, 76, 26]
25272         [32, 1235, 107, 38]
142571                    [2, 79]
80748                [17, 130, 2]
123831                   [88, 12]
137896                       [21]
7047         [32, 38, 10, 12, 25]
121854             [18, 1235, 38]
125641              [236, 38, 15]
53375                   [100, 21]
146556    [70, 107, 12, 15, 1235]
106926      [66, 38, 359, 12, 26]
98478               [41, 250, 38]
50442               [100, 21, 15]
149972           [41, 10, 76, 38]
116330                         []
40952                        [12]
137475              [41, 38, 247]
58078             [1, 187, 5, 38]
147766                   [12, 85]

                                                                      \
                                                information interest
track_id
15917                                                   NaN     1545
25272                                                   NaN      641
142571                                                  NaN     1783
80748                                                   NaN      420
123831                                                  NaN     2065
137896                                                  NaN     1666
7047                                                    NaN     5591
121854                                                  NaN    12363
125641                                                  NaN     2034
53375                                                   NaN     1365
146556                                                  NaN     5112
106926                                                  NaN     3423
98478                                                   NaN      155
50442                                                   NaN     2512
149972                                                  NaN      905
116330                                                  NaN      347
40952                                                   NaN      295
137475                                                  NaN      189
58078     <p>Theo Nabicht, soprano saxophone and Alexand...     9859
147766                                                  NaN      314

                                                                           \
         language_code                                            license
track_id
15917               en  Attribution-NonCommercial-ShareAlike 3.0 Inter...
25272              NaN  Attribution-Noncommercial-No Derivative Works ...
142571             NaN  Attribution-Noncommercial-Share Alike 3.0 Unit...
80748              NaN  Attribution-NonCommercial-NoDerivatives (aka M...
123831             NaN  Attribution-Noncommercial-Share Alike 3.0 Unit...
137896             NaN               Attribution-NonCommercial-ShareAlike
7047                en                                        Attribution
121854             NaN        Attribution-NonCommercial 3.0 International
125641             NaN               Attribution-NonCommercial-ShareAlike
53375              NaN  Attribution-Noncommercial-No Derivative Works ...
146556             NaN                                        Attribution
106926             NaN  Attribution-NonCommercial-ShareAlike 3.0 Inter...
98478              NaN  Attribution-NonCommercial-NoDerivatives (aka M...
50442              NaN  Attribution-Noncommercial-Share Alike 3.0 Unit...
149972             NaN  Creative Commons Attribution-NonCommercial-NoD...
116330             NaN  Creative Commons Attribution-NonCommercial-NoD...
40952              NaN  Attribution-Noncommercial-No Derivative Works ...
137475             NaN  Creative Commons Attribution-NonCommercial-NoD...
58078              NaN  Attribution-NonCommercial-NoDerivatives (aka M...
147766             NaN  Attribution-NonCommercial-NoDerivatives (aka M...

                                            \
         listens lyricist number publisher
track_id
15917        161      NaN      2       NaN
25272        435      NaN     11       NaN
142571      1289      NaN      8       NaN
80748        355      NaN      2       NaN
123831      1561      NaN      7       NaN
137896      1297      NaN      7       NaN
7047        4676      NaN      2       NaN
121854      9458      NaN      0       NaN
125641      1682      NaN      4       NaN
53375        884      NaN      9       NaN
146556      4340      NaN      9       NaN
106926      2445      NaN      5       NaN
98478         74      NaN      3       NaN
50442       1177      NaN     11       NaN
149972       842      NaN      2       NaN
116330       236      NaN      0       NaN
40952        110      NaN     11       NaN
137475       108      NaN      2       NaN
58078       8518      NaN      0       NaN
147766       257      NaN      9       NaN

                                                             \
                                                       tags
track_id
15917                                                    []
25272                                                    []
142571                                                   []
80748                                                    []
123831                                                   []
137896                                                   []
7047                                                     []
121854                                                   []
125641                                                   []
53375                                                    []
146556            ['the second circle', '24-bit', 'era 3b']
106926    ['aniqatia', 'vocal', 'drums', 'music for vide...
98478                                                    []
50442                                                    []
149972                                                   []
116330                                                   []
40952                                                    []
137475            ['live', 'post-concrete', 'dark ambient']
58078                                                    []
147766                                                   []


                                              title
track_id
15917                                        Tropic
25272                    In Memory of Betty Page 22
142571                                      Senegal
80748                                 Buenek Medley
123831                          Cares For the Waves
137896              The Cafe featuring Donnie Ozone
7047                                         Swords
121854                                         Cree
125641                    Bit War (ft. Perturbator)
53375                            Future on the Road
146556            Tscercal [feat. Elizabeth Veldon]
106926                                    Shark Bay
98478                                           J+G
50442                               Wolftooth Gears
149972                              P-M:TAPE-FACE B
116330                                    Beat Down
40952                          Strychnine Dandelion
137475    Zreen Toyz - Dans les labyrinthes infinis
58078                                       Unisons
147766                                 Rubber Trees

In [108]:
tracks_df.track.genres.value_counts()

[21]                    2735
[15]                    2689
[]                      2231
[12]                    1896
[1, 30, 38, 41, 247]    1633
                        ...
[12, 542]                  1
[92, 602]                  1
[102, 189]                 1
[14, 30, 92]               1
[10, 12, 169]              1
Name: genres, Length: 4768, dtype: int64

In [109]:
tracks_df['valid_genre'] = tracks_df.track.genres.apply(lambda x: x.strip('][').split(', ') if x != '[]' else None)

In [110]:
tracks_df.valid_genre.dropna()

track_id
2                  [21]
3                  [21]
5                  [21]
10                 [10]
20            [76, 103]
              ...
155316             [25]
155317             [25]
155318             [25]
155319             [25]
155320    [10, 12, 169]
Name: valid_genre, Length: 104343, dtype: object

In [111]:
tracks_df.track.genre_top

track_id
2         Hip-Hop
3         Hip-Hop
5         Hip-Hop
10            Pop
20            NaN
           ...
155316       Rock
155317       Rock
155318       Rock
155319       Rock
155320        NaN
Name: genre_top, Length: 106574, dtype: object

In [112]:
tracks_df.track

,bit_rate,comments,composer,date_created,date_recorded,duration,favorites,genre_top,genres,genres_all,information,interest,language_code,license,listens,lyricist,number,publisher,tags,title
track_id,,,,,,,,,,,,,,,,,,,,
2,256000,0,NaN,2008-11-26 01:48:12,2008-11-26 00:00:00,168,2,Hip-Hop,[21],[21],NaN,4656,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293,NaN,3,NaN,[],Food
3,256000,0,NaN,2008-11-26 01:48:14,2008-11-26 00:00:00,237,1,Hip-Hop,[21],[21],NaN,1470,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514,NaN,4,NaN,[],Electric Ave
5,256000,0,NaN,2008-11-26 01:48:20,2008-11-26 00:00:00,206,6,Hip-Hop,[21],[21],NaN,1933,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151,NaN,6,NaN,[],This World
10,192000,0,Kurt Vile,2008-11-25 17:49:06,2008-11-26 00:00:00,161,178,Pop,[10],[10],NaN,54881,en,Attribution-NonCommercial-NoDerivatives (aka M...,50135,NaN,1,NaN,[],Freeway
20,256000,0,NaN,2008-11-26 01:48:56,2008-01-01 00:00:00,311,0,NaN,"[76, 103]","[17, 10, 76, 103]",NaN,978,en,Attribution-NonCommercial-NoDerivatives (aka M...,361,NaN,3,NaN,[],Spiritual Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155316,320000,0,NaN,2017-03-30 15:23:34,NaN,162,1,Rock,[25],"[25, 12]",NaN,122,NaN,Creative Commons Attribution-NonCommercial-NoD...,102,NaN,3,NaN,[],The Auger
155317,320000,0,NaN,2017-03-30 15:23:36,NaN,217,1,Rock,[25],"[25, 12]",NaN,194,NaN,Creative Commons Attribution-NonCommercial-NoD...,165,NaN,4,NaN,[],Let's Skin Ruby
155318,320000,0,NaN,2017-03-30 15:23:37,NaN,404,2,Rock,[25],"[25, 12]",NaN,214,NaN,Creative Commons Attribution-NonCommercial-NoD...,168,NaN,6,NaN,[],My House Smells Like Kim Deal/Pulp
155319,320000,0,NaN,2017-03-30 15:23:39,NaN,146,0,Rock,[25],"[25, 12]",NaN,336,NaN,Creative Commons Attribution-NonCommercial-NoD...,294,NaN,5,NaN,[],The Man With Two Mouths
155320,320000,0,NaN,2017-03-30 09:15:36,NaN,198,1,NaN,"[10, 12, 169]","[169, 10, 12, 9]",NaN,972,NaN,Attribution-NonCommercial,705,NaN,7,NaN,"['ballad', 'epic', 'rockabilly', 'curse', 'hex...",Another Trick Up My Sleeve (Instrumental)

In [126]:
## Get complete genre structure
def get_all_structure(estrutura,df_genres):
    ## Get structure from df_genres
    def get_all_structure_from_df(estrutura,df_genres,structure=[]):
        if estrutura == 0:
            return structure
        else:
            structure.append(estrutura)
            get_all_structure_from_df(df_genres[df_genres["genre_id"]==int(estrutura)].parent.values[0],df_genres,structure)
            return structure
    
    return get_all_structure_from_df(estrutura,df_genres,structure=[])

In [115]:
tracks_df['first_genre_id'] = tracks_df.valid_genre.apply(lambda x:x[-1] if x != None else None)

In [116]:
tracks_df = tracks_df[['valid_genre','first_genre_id']]

In [117]:
tracks_df.sample(20)

                  valid_genre first_genre_id

track_id
27814             [1, 38, 41]             41
1754                     [12]             12
83416                    [15]             15
13693     [1, 10, 15, 38, 76]             76
61506             [741, 1060]           1060
22822            [15, 32, 38]             38
71077                    [12]             12
21705           [15, 38, 224]            224
142900        [18, 456, 1235]           1235
109336            [1, 15, 38]             38
121861               [15, 76]             76
58311             [2, 12, 38]             38
57840            [3, 17, 103]            103
132806        [18, 456, 1235]           1235
76652            [12, 15, 38]             38
94773                [32, 38]             38
85895               [41, 107]            107
30170                    [85]             85
7124                     [17]             17
75683                [12, 25]             25

In [118]:
tracks_df.dropna(inplace=True)

In [125]:
tracks_df

            valid_genre first_genre_id full_genre_id

track_id
2                  [21]             21          None
3                  [21]             21          None
5                  [21]             21          None
10                 [10]             10          None
20            [76, 103]            103          None
...                 ...            ...           ...
155316             [25]             25          None
155317             [25]             25          None
155318             [25]             25          None
155319             [25]             25          None
155320    [10, 12, 169]            169          None

[104343 rows x 3 columns]

In [122]:
tracks_df

            valid_genre first_genre_id

track_id
2                  [21]             21
3                  [21]             21
5                  [21]             21
10                 [10]             10
20            [76, 103]            103
...                 ...            ...
155316             [25]             25
155317             [25]             25
155318             [25]             25
155319             [25]             25
155320    [10, 12, 169]            169

[104343 rows x 2 columns]

In [127]:
tracks_df.loc[:,'full_genre_id'] = tracks_df.first_genre_id.apply(lambda x: get_all_structure(x,genres_df))

In [128]:
tracks_df.full_genre_id.value_counts()

[38]             6517
[1235]           6055
[76, 10]         4131
[107, 1235]      3991
[103, 17]        3487
                 ...
[493, 651, 9]       4
[189, 65, 20]       4
[173, 86, 2]        4
[444, 5]            2
[7, 20]             2
Name: full_genre_id, Length: 159, dtype: int64

In [136]:
tracks_df.reset_index(inplace=True)

In [137]:
def find_path(track_id,dataset_path):
    track_id = track_id.zfill(6)
    folder_id = track_id[0:3]
    file_path = os.path.join(dataset_path,folder_id,track_id+'.mp3')
    return file_path

In [138]:
tracks_df['file_path'] = tracks_df.track_id.apply(lambda x: find_path(str(x),args.dataset_path))

In [139]:
tracks_df.iloc[0].file_path

    /mnt/disks/data/fma/fma_large/000/000002.mp3
Name: 0, dtype: object

In [140]:
def valid_music(file_path):
    try:
        # we start by instantiating the audio loader:
        loader = MonoLoader(filename=file_path)

        return True
    except:
        return False

In [141]:
valid_music('/mnt/disks/data/fma/fma_large/000/000002.mp3')

True

In [142]:
tracks_df[['track_id','file_path']].shape

(104343, 2)

In [143]:
tracks_df.shape

(104343, 5)

### Delete all crashed files

In [144]:
processed = pd.read_csv(os.path.join(train_path,"tracks.csv"))

In [145]:
tracks_df = tracks_df[tracks_df['Valid'] == True]

KeyError: 'Valid'

### Parse of label to structure

In [19]:
### Function for parse label to sctructure of hierarhical scheme

def parse_label(label):
    label = label.split('-')
    # preencher com 0 no caso de haver menos de 5 níveis
    labels = np.zeros(5,dtype=int)
    for i, label in enumerate(label):
        if i == 5:
            break
        # Aqui você pode fazer a conversão do label em um índice inteiro usando um dicionário ou outro método
        # Neste exemplo, estou apenas usando a posição da label na lista como índice
        labels[i] = label
    return labels

In [20]:
tracks_df.full_genre_id.value_counts()

15          20307
1-38         8678
38           6692
12           6635
10           5906
            ...
444-5           2
810-13          2
502-46-2        2
173-86-2        1
170-13          1
Name: full_genre_id, Length: 148, dtype: int64

In [21]:
tracks_df['labels'] = tracks_df.full_genre_id.apply(lambda x: parse_label(x))

In [22]:
def convert_label_to_string(x,level=2):
    return '-'.join([str(value) for value in x[:level]])

In [23]:
tracks_df['labels_1'] = tracks_df.labels.progress_apply(lambda x: str(x[:1][0]))
tracks_df['labels_2'] = tracks_df.labels.progress_apply(lambda x: convert_label_to_string(x,level=2))
tracks_df['labels_3'] = tracks_df.labels.progress_apply(lambda x: convert_label_to_string(x,level=3))
tracks_df['labels_4'] = tracks_df.labels.progress_apply(lambda x: convert_label_to_string(x,level=4))
tracks_df['labels_5'] = tracks_df.labels.progress_apply(lambda x: convert_label_to_string(x,level=5))

  0%|          | 0/104186 [00:00<?, ?it/s]

  0%|          | 0/104186 [00:00<?, ?it/s]

  0%|          | 0/104186 [00:00<?, ?it/s]

  0%|          | 0/104186 [00:00<?, ?it/s]

  0%|          | 0/104186 [00:00<?, ?it/s]

In [24]:
tracks_df.labels_2.unique()

array(['21-0', '10-0', '76-10', '45-12', '1-38', '17-0', '4-0', '25-12',
       '26-12', '30-38', '27-12', '15-0', '12-0', '31-12', '32-38',
       '89-25', '36-12', '3-0', '37-4', '41-38', '43-65', '79-2', '46-2',
       '11-14', '38-0', '2-0', '47-38', '33-17', '49-17', '250-38',
       '138-20', '53-45', '58-12', '22-38', '103-17', '64-25', '66-12',
       '42-15', '70-12', '71-25', '5-0', '98-12', '74-4', '85-12',
       '166-65', '188-20', '63-9', '9-0', '118-2', '111-25', '109-25',
       '97-4', '117-2', '92-2', '77-2', '13-0', '137-9', '102-2', '8-0',
       '185-15', '101-31', '224-38', '94-17', '20-0', '125-38', '180-17',
       '113-26', '7-20', '100-21', '906-4', '14-0', '538-18', '6-38',
       '107-1235', '18-1235', '286-15', '236-15', '90-53', '88-12',
       '297-15', '65-20', '337-15', '86-2', '763-16', '314-12', '167-31',
       '172-2', '179-4', '214-92', '19-14', '184-15', '181-15', '359-12',
       '361-109', '362-10', '183-15', '374-20', '81-92', '322-5',
       '240-297', '186-38', '187-5', '440-12', '247-38', '171-2',
       '311-13', '296-15', '468-15', '182-15', '495-15', '130-2',
       '1060-46', '443-5', '16-6', '542-21', '491-468', '456-38',
       '514-38', '169-9', '404-85', '177-2', '1193-763', '741-130',
       '524-130', '360-6', '808-46', '659-5', '400-182', '189-65',
       '811-21', '539-21', '439-31', '1235-0', '810-13', '442-5', '651-9',
       '267-1235', '83-21', '504-2', '695-15', '378-20', '428-20',
       '602-79', '444-5', '1032-102', '502-46', '173-86', '170-13'],
      dtype=object)

In [25]:
tracks_df.to_csv(os.path.join(train_path,"tracks.csv"),index=False)

In [14]:
tracks_df = pd.read_csv(os.path.join(train_path,"tracks.csv"))

In [21]:
labels_level_1 = tracks_df.labels_1.unique()
labels_level_2 = tracks_df.labels_2.unique()
labels_level_3 = tracks_df.labels_3.unique()
labels_level_4 = tracks_df.labels_4.unique()
labels_level_5 = tracks_df.labels_5.unique()

In [22]:
categories_df = pd.DataFrame(
    {'level5':labels_level_5,
    'level4':labels_level_4,
    'level3':labels_level_3,
    'level2':labels_level_2,
    'level1':labels_level_1})

In [23]:
def get_labels_name(x,genres_df):
    levels = 5
    full_name = []
    last_level = 0
    genre_root = ""
    for genre in x.split('-'):
        genre_df = genres_df[genres_df['genre_id'] == int(genre)]
        if genre_df.empty:
            genre_name = genre_root 
        else:
            genre_name = genre_df.title.values.tolist()[0]
            genre_root = genre_name
        
        full_name.append(genre_name)
    full_name = '>'.join(full_name)
        
    return full_name
    # return genres_df[genres_df['genre_id'] == int(x)].title.values.tolist()[0]

In [24]:
categories_df['level5_name'] = categories_df.level5.apply(lambda x: get_labels_name(x,genres_df))

In [25]:
categories_df['level5_name']

0                Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop>Hip-Hop
1                                    Pop>Pop>Pop>Pop>Pop
2                       Experimental Pop>Pop>Pop>Pop>Pop
3                          Loud-Rock>Rock>Rock>Rock>Rock
4      Avant-Garde>Experimental>Experimental>Experime...
                             ...
143     Symphony>Classical>Classical>Classical>Classical
144    Turkish>Middle East>International>Internationa...
145    Cumbia>Latin America>International>Internation...
146    N. Indian Traditional>Indian>International>Int...
147    Easy Listening: Vocal>Easy Listening>Easy List...
Name: level5_name, Length: 148, dtype: object

In [27]:
def __create_labels__(categories_df):
    data = {
        "label1": {},
        "label2": {},
        "label3": {},
        "label4": {},
        "label5": {},
        "label1_inverse": [],
        "label2_inverse": [],
        "label3_inverse": [],
        "label4_inverse": [],
        "label5_inverse": [],
        "label1_name": {},
        "label2_name": {},
        "label3_name": {},
        "label4_name": {},
        "label5_name": {},
    }

    for idx, cat in enumerate(set(categories_df.level1.values.tolist())):
        data['label1'][cat] = idx
        data['label1_inverse'].append(cat)
        data['label1_count'] = idx + 1

    for idx, cat in enumerate(set(categories_df.level2.values.tolist())):
        data['label2'][cat] = idx
        data['label2_inverse'].append(cat)
        data['label2_count'] = idx + 1
        
    for idx, cat in enumerate(set(categories_df.level3.values.tolist())):
        data['label3'][cat] = idx
        data['label3_inverse'].append(cat)
        data['label3_count'] = idx + 1

    for idx, cat in enumerate(set(categories_df.level4.values.tolist())):
        data['label4'][cat] = idx
        data['label4_inverse'].append(cat)
        data['label4_count'] = idx + 1
        
    for idx, cat in enumerate(set(categories_df.level5.values.tolist())):
        data['label5'][cat] = idx
        data['label5_inverse'].append(cat)
        data['label5_count'] = idx + 1
        
    for cat5,cat4,cat3,cat2,cat1,name5 in categories_df.values:
        
        name1 = '>'.join(name5.split('>')[:1])
        name2 = '>'.join(name5.split('>')[:2])
        name3 = '>'.join(name5.split('>')[:3])
        name4 = '>'.join(name5.split('>')[:4])
        
        
        data['label1_name'][cat1] = name1
        data['label2_name'][cat2] = name2
        data['label3_name'][cat3] = name3
        data['label4_name'][cat4] = name4
        data['label5_name'][cat5] = name5
        
    return data

In [28]:
with open(categories_labels_path, 'w+') as f:
    f.write(json.dumps(__create_labels__(categories_df)))